#!/bin/bash

# Removes Clovis index (only one so far), creates a new one
# instead of it, and inits a root inode within the index.

log_exec_bin() {
    echo "exec >>> ($*)"
    $@
    local rc=$?
    echo "exec <<< ($rc)"
    return $rc
}

clovis_exec() {
    local kvsns_ini="/etc/kvsns.d/kvsns.ini"
    # TODO: 5 awk calls is overkill, use a single awk script here or
    # add a special binary for create/drop calls.
    local local_addr=$(awk '/local_addr/ { print $3; }' $kvsns_ini)
    local ha_addr=$(awk '/ha_addr/ { print $3; }' $kvsns_ini)
    local proc_fid=$(awk '/proc_fid/ { print $3; }' $kvsns_ini)
    local profile=$(awk '/profile/ { print $3; }' $kvsns_ini)
    local kvs_fid=$(awk '/kvs_fid/ { print $3; }' $kvsns_ini)
    local CMD="m0clovis -l $local_addr -h $ha_addr -p $profile -f $proc_fid $* $kvs_fid"

    log_exec_bin $CMD
}

kvs_create_index() {
    clovis_exec index create
}

kvs_drop_index() {
    clovis_exec index drop
}

kvs_reset_index() {
    kvs_drop_index && kvs_create_index
}

kvsns_init_cmd() {
    local CMD=kvsns_init
    log_exec_bin $CMD
}


kvs_reset_index && kvsns_init_cmd
